name: goodtimes
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  cloud_firestore: ^4.7.1
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firebase_storage: ^11.2.1
  get: 4.6.5
  url_launcher: ^6.1.11
  universal_html: ^2.2.2
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  imageview360: ^1.3.0
  flutter_bounce: ^1.1.0
  flutter_zoom_drawer: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
    - assets/shows/
  fonts:
    - family: airbnb
      fonts:
        - asset: assets/font/AirbnbCereal_W_Bd.otf
